media:
  input: src/assets/images
  output: ~/assets/images
content:
  - name: Products
    label: Products
    type: collection
    path: 'src/data/post'
    view:
      fields: [ title, published, publishDate ]
    fields:
      - name: title
        label: Title
        type: string
      - name: stucture
        label: Stucture
        type: rich-text
      - name: lighting
        label: Lighting
        type: rich-text
      - name: category
        label: Category
        type: string
        default: Products
      - name: tags
        label: Tag
        list: true
        type: select
        options:
          values: [ Led bathroom mirror, Led Framed mirror, Medicine cabinet mirror, Acrylic lighting mirror, Hollywood  mirror ]
      - name: image
        label: Cover
        type: image
        options:
          path: src/assets/images
          extensions: [ jpg, jpeg, png ]
      - name: publishDate
        label: Date
        type: date
      - name: body
        label: Content
        type: rich-text