media:
  input: src/assets/images
  output: /media
content:
  - name: Products
    label: Products
    type: collection
    path: 'src/data/post'
    view:
      fields: [ title, published, date ]
    fields:
      - name: title
        label: Title
        type: string
      - name: excerpt
        label: Excerpt
        type: string
      - name: category
        label: Category
        type: string
      - name: tag
        label: Tag
        type: select
        options:
        values: [ Tech, News, Sports ]
      - name: cover
        label: Cover
        type: image
        list: true
        options:
          path: src/assets/images
          extensions: [ jpg, jpeg, png ]
      - name: date
        label: Date
        type: date
      - name: body
        label: Content
        type: rich-text