media:
  input: src/assets/images
  output: ~/assets/images
content:
  - name: Products
    label: Products
    type: collection
    path: 'src/data/post'
    view:
      fields: [ title, published, publishDate ]
    fields:
      - name: title
        label: 标题
        type: string
      - name: excerpt
        label: 简介
        type: string
      - name: stucture
        label: Stucture
        type: rich-text
      - name: lighting
        label: Lighting
        type: rich-text
      - name: tags
        label: 分类
        list: true
        type: select
        options:
          values: [ Led bathroom mirror, Framed mirror, Medicine cabinet mirror, LED Makeup Mirror, Hollywood  mirror ]
      - name: image
        label: Cover
        type: image
        options:
          path: src/assets/images
          extensions: [ jpg, jpeg, png ]
      - name: publishDate
        label: Date
        type: date
      - name: body
        label: 介绍
        type: rich-text